language: bash
services: docker

env:
  global:
    - PROJECT=gitlab-node
    - NAMESPACE=plasmops
    - PUSH_NAMESPACES=plasmops

install:
  - curl -sSL https://github.com/stackfeed/ci-scripts/raw/master/install.sh | sh -s

before_script:
  - export PATH=$PATH:~/ci-scripts

script:
  - docker-build $NAMESPACE/$PROJECT -f ./Dockerfile . || exit $?

# deploy containers to hub.docker.com
after_deploy:
  - |
      # Skip if we are not in the push namespace list
      ( echo "$PUSH_NAMESPACES" | grep -qw "${TRAVIS_REPO_SLUG%/*}" ) || exit 0
      docker-push -r "^$NAMESPACE/$PROJECT:?.*"

deploy:
  - provider: script
    script: /bin/true
    on:
      branch: master

after_script:
  - docker images

notifications:
  webhooks:
    urls:
      - https://hooks.microbadger.com/images/plasmops/gitlab-node/${MICROBADGER_TOKEN}
    on_success: always
    on_failure: never
    on_start:   never
    on_cancel:  never
    on_error:   never
